CREATE TABLE IF NOT EXISTS `#__productcat_node` (
 `catid` smallint(5) unsigned NOT NULL AUTO_INCREMENT,
 `filid` int(10) unsigned NOT NULL DEFAULT '0',
 `namekey` varchar(100) NOT NULL,
 `alias` varchar(150) NOT NULL,
 `type` tinyint(3) unsigned NOT NULL DEFAULT '0',
 `lft` mediumint(8) unsigned NOT NULL DEFAULT '0',
 `rgt` mediumint(8) unsigned NOT NULL DEFAULT '0',
 `parent` mediumint(8) unsigned NOT NULL DEFAULT '0',
 `rolid` smallint(5) unsigned NOT NULL DEFAULT '1',
 `ordering` int(10) unsigned NOT NULL DEFAULT '0',
 `publish` tinyint(4) NOT NULL DEFAULT '0',
 `modified` int(10) unsigned NOT NULL DEFAULT '0',
 `created` int(10) unsigned NOT NULL DEFAULT '0',
 `author` int(10) unsigned NOT NULL DEFAULT '0',
 `params` text NOT NULL,
 `depth` tinyint(3) unsigned NOT NULL DEFAULT '0',
 `numpid` int(10) unsigned NOT NULL DEFAULT '0',
 `vendid` int(10) unsigned NOT NULL DEFAULT '1',
 `uid` int(10) unsigned NOT NULL DEFAULT '0',
 `publishstart` int(10) unsigned NOT NULL DEFAULT '0',
 `publishend` int(10) unsigned NOT NULL DEFAULT '0',
 `cssclass` varchar(100) NOT NULL,
 `prodtypid` smallint(5) unsigned NOT NULL DEFAULT '0',
 `layout` tinyint(3) unsigned NOT NULL DEFAULT '1',
 `blocked` tinyint(3) unsigned NOT NULL DEFAULT '0',
 `hits` int(10) unsigned NOT NULL DEFAULT '0',
 `featured` int(10) unsigned NOT NULL DEFAULT '0',
 `site_id` varchar(255) NOT NULL,
 `numpidsub` int(10) unsigned NOT NULL DEFAULT '0',
 `restrictcategory` tinyint(4) NOT NULL DEFAULT '0',
 PRIMARY KEY (`catid`),
 UNIQUE KEY `UK_productcat_node_namekey` (`namekey`),
 KEY `IX_productcat_node_ordering` (`ordering`),
 KEY `IX_productcat_node_parent` (`parent`),
 KEY `IX_productcat_node_publish_rolid` (`publish`,`rolid`),
 KEY `IX_productcat_node_publishstart_publishend` (`publishstart`,`publishend`),
 KEY `IX_productcat_node_prodtypid` (`prodtypid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;